version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: ''
    volumes:
       - '/opt/containers/pi-hole/pihole/:/etc/pihole/'
       - '/opt/containers/pi-hole/dnsmasq/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
