default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

http:
  server_port: 8123
  cors_allowed_origins:
    - https://google.com/
    - https://www.home-assistant.io/
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
  ip_ban_enabled: true
  login_attempts_threshold: 5


automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
